server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/victorvelez/spring-cloud-starter.git
                    searchPaths: config-server
management:
    security:
        enabled: false